### ISSUE TITLE
Error: EISDIR: illegal operation on a directory, read

### ISSUE THREAD

**Issue by sidaf** [kevinkub/homebridge-aedes#2]
**Describe The Bug:**
When enabling the persistence option, homebridge is unable to restart due to an exception being thrown which forces a SIGTERM, which ultimately culminates in an endless restart loop. The only way to get homebridge to start is to disable the persistence option (i.e. set to false) and delete the /var/lib/homebridge/persist/aedes-mqtt folder.

I checked the permissions of the folder, and the files within, and it seems consistent with the other files.

```
$ ls -lh
total 16K
-rw-r--r-- 1 pi pi  424 Feb  3 19:19 AccessoryInfo.***.json
drwxr-xr-x 2 pi pi 4.0K Feb  3 19:19 aedes-mqtt
-rw-r--r-- 1 pi pi 7.0K Feb  3 19:16 IdentifierCache.***.json
$ cd aedes-mqtt/
$ ls -l
total 0
-rw-r--r-- 1 pi pi 0 Feb  3 19:20 incoming.db
-rw-r--r-- 1 pi pi 0 Feb  3 19:20 outgoing.db
-rw-r--r-- 1 pi pi 0 Feb  3 19:20 retained.db
-rw-r--r-- 1 pi pi 0 Feb  3 19:20 subscriptions.db
-rw-r--r-- 1 pi pi 0 Feb  3 19:20 wills.db
```

**To Reproduce:**
Set persistance option to true in the config file or via the GUI.

**Expected behavior:**
Homebridge to restart successfully without any errors. 

**Logs:**

```
[03/02/2021, 19:21:31] Error: EISDIR: illegal operation on a directory, read
    at Object.readSync (fs.js:592:3)
    at tryReadSync (fs.js:366:20)
    at Object.readFileSync (fs.js:403:19)
    at LocalStorage.parseDirSync (/usr/local/lib/node_modules/homebridge/node_modules/node-persist/src/local-storage.js:637:35)
    at LocalStorage.parseDataDirSync (/usr/local/lib/node_modules/homebridge/node_modules/node-persist/src/local-storage.js:572:21)
    at LocalStorage.initSync (/usr/local/lib/node_modules/homebridge/node_modules/node-persist/src/local-storage.js:145:14)
    at HAPStorage.storage (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/model/HAPStorage.ts:23:25)
    at Function.HAPStorage.storage (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/model/HAPStorage.ts:11:26)
    at Function.AccessoryInfo.load (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/model/AccessoryInfo.ts:204:28)
    at Bridge.Accessory._this.publish (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:890:41)
[03/02/2021, 19:21:31] Got SIGTERM, shutting down Homebridge...
[03/02/2021, 19:21:31] [Aedes MQTT] Stopping Aedes MQTT broker "Aedes MQTT".
[03/02/2021, 19:21:35] [Homebridge UI] Changes to config.json saved.
[03/02/2021, 19:21:36] [Hue] goodbye
[03/02/2021, 19:21:36] [HB Supervisor] Homebridge Process Ended. Code: 143, Signal: null
[03/02/2021, 19:21:41] [HB Supervisor] Restarting Homebridge...
```

**Plugin Config:**

```json
       {
            "name": "Aedes MQTT",
            "persistence": true,
            "auth": {
                "isEnabled": true,
                "username": "***",
                "password": "***"
            },
            "platform": "HomebridgeAedes"
        }
```

**Environment:**

* **Plugin Version**: 1.0.0
* **Homebridge Version**: 1.1.7
* **Node.js Version**: v14.15.4
* **NPM Version**: 6.14.11
* **Operating System**: Raspbian

**Comment by kevinkub** [comment]
I ran into the issue myself just yesterday. It seems from a first look that homebridge is no longer able to work with subfolders inside the persistence folder. I will try to fix that tomorrow. Thanks for creating the bug report.
